### ISSUE TITLE
Crash after update to 2.7 - Host Netlify

### ISSUE THREAD

**Issue by laurent-d** [umami-software/umami#2312]
### Describe the Bug

Hello just for your information after make an update from 2.6.2 to 2.7 i have this crash message on login page :
Host Netlify - DB Supabase

**This function has crashed
An unhandled error in the function code triggered the following message:**

`Runtime.ImportModuleError - Error: Cannot find module 'styled-jsx/style' Require stack: - /var/task/node_modules/next/dist/server/require-hook.js - /var/task/node_modules/next/dist/server/next-server.js - /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js - /var/task/___netlify-handler.js - /var/runtime/index.mjs`

**Stack trace**

`Runtime.ImportModuleError: Error: Cannot find module 'styled-jsx/style'
Require stack:
- /var/task/node_modules/next/dist/server/require-hook.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js
- /var/task/___netlify-handler.js
- /var/runtime/index.mjs
    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)
    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)
    at async start (file:///var/runtime/index.mjs:1256:23)
    at async file:///var/runtime/index.mjs:1262:1`
    
    Hope it helps

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Netlify

**Comment by franciscao633** [comment]
I found a similar error in the [netlify forums](https://answers.netlify.com/t/runtime-importmoduleerror-error-cannot-find-module-styled-jsx-nextjs-nextauth/95281/4). Can you see if those steps help?

**Comment by mlaplante** [comment]
Gave this a quick go by pinning the netlify runtime back to 4.36.1 and its still throwing the same styled error.

**Comment by laurent-d** [comment]
Thanks @franciscao633 same issue that @mlaplante :/ with overriding next plugin from netlify

**Comment by franciscao633** [comment]
I found a even more recent [Netlify Post](https://answers.netlify.com/t/runtime-importmoduleerror-error-cannot-find-module-styled-jsx-style/102375/5). Looks like Next 13.5 isn't compatible with Netlify. I downgraded to Next 13.4.19 with success.

**Comment by mlaplante** [comment]
@franciscao633 Great find, that does indeed seem to resolve the issue in the short term
