### ISSUE TITLE
Failed to load multiple resources: 404 on v2.6.*

### ISSUE THREAD

**Issue by bertusdebruin** [umami-software/umami#2287]
### Describe the Bug

The 'View details page' for any added website, won't work in v2.6.0, v2.6.1 and v2.6.2 as the Umami writes an empty white page. 
And multiple sources that cannot be found as can be seen in the console of Edge, Chromium, Chrome and Firefox.

Update from v2.5 to v2.6.0, v2.6.1 and v2.6.2 won't fix the problem.
Update from v2.5 to v2.6.0, to v2.6.1 and finally v2.6.2 won't fix the problem.
The same for a fresh v2.6.0, v2.6.1 and v2.6.2 installation based on https://umami.is/docs/install
Going back to v2.5 or installing a fresh v2.5 fixes the problem immediately.

Please fix, thanks and have a nice day.

System: NodeJS v18.17.1 and MariaDB 10.6

General 

Failed to load resource: the server responded with a status of 401 ()
_next/static/chunks/…5ca114778eb3ce.js:1 
 Failed to load resource: the server responded with a status of 404 ()
_next/static/chunks/…5ca114778eb3ce.js:1 
 Failed to load resource: the server responded with a status of 404 ()
main-ae1ac61e909dd293.js:1 Error: Failed to load script: /_next/static/chunks/pages/websites/%5Bid%5D-765ca114778eb3ce.js
    at t.onerror (main-ae1ac61e909dd293.js:1:25663)

And sources that cannot be found on the specific View details > page for any added website.

GET https://testdomain.com/_next/static/chunks/pages/website ca911ba3-37cc-4674-9cb7-3a3f5fa8bb06:1
﻿
/testdomain.com/_next/static/chunks/pages/websites/%5Bid%5D-765ca114778eb3ce.js net::ERR_ABORTED 404

### Database

MySQL

### Which browser are you using? (if relevant)

Chrome, Edge, Chromium without extensions 

### How are you deploying your application? (if relevant)

NodeJS v18.17.1

**Comment by adrinux** [comment]
Do you have a proxy in front of Umami, such as nginx? Then this might help [issue 2269](https://github.com/umami-software/umami/issues/2269)

**Comment by bertusdebruin** [comment]
> Do you have a proxy in front of Umami, such as nginx? Then this might help [issue 2269](https://github.com/umami-software/umami/issues/2269)

Thanks m8! Fixed the problem. It remains strange since Umami has been working fine over here, for over a year with the previous: Nginx configuration with: / . I will continue the discussion in the topic you cite. To centralize the possible problem so that everyone can have use the same solution, eventually.

**Comment by bertusdebruin** [comment]
@adrinux Seems as bug #2269 is closed: without debug what exactly casus the problem. 
As Umami is working fine via Nginx as a reverse proxy (proxy_pass) up to version 2.5. 
Anyone here on GitHub with an analysis of how, what and why?
