### ISSUE TITLE
Error when opening user websites in the settings

### ISSUE THREAD

**Issue by orilights** [umami-software/umami#2207]
### Describe the Bug

After upgrading Umami to 2.5.0, I can't open user websites in the settings.

![image](https://github.com/umami-software/umami/assets/61224409/af5d8e00-5e02-4619-87ce-dccd85835907)

Get error when click [Websites]

![image](https://github.com/umami-software/umami/assets/61224409/84fcc324-535b-4148-ad94-0bebca9ee7fe)

I don't see any error logs on the server, it seems to be entirely a frontend issue.

After downgrading umami to 2.4.1 everything works fine.

### Database

MySQL

### Relevant log output

```shell
framework-73b8966a3c579ab0.js:9  TypeError: j is not a function
    at w (420-0f9d38acd2802d57.js:1:1480)
    at _app-663bdfebd59d6c1b.js:49:320775
    at uI (framework-73b8966a3c579ab0.js:9:84130)
    at oU (framework-73b8966a3c579ab0.js:9:113201)
    at framework-73b8966a3c579ab0.js:9:111581
    at oI (framework-73b8966a3c579ab0.js:9:111647)
    at oC (framework-73b8966a3c579ab0.js:9:96276)
    at r4 (framework-73b8966a3c579ab0.js:9:44778)
    at framework-73b8966a3c579ab0.js:9:93632
```

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

Docker

**Comment by iamyashkhandelwal** [comment]
Hey @mikecao , Can you assign this to me?
I'm working on it.

**Comment by iamyashkhandelwal** [comment]
Hey @mikecao , here is the PR for this issue - https://github.com/umami-software/umami/pull/2209
Thank you

**Comment by mikecao** [comment]
Fixed in v2.6.0.
